#!/usr/bin/env node
/**
 * Pull OpenAPI from the running API and emit packages/schemas/src/api.ts.
 *
 * Usage:
 *   pnpm --filter @jobcopilot/schemas gen
 *
 * Env:
 *   OPENAPI_URL  default http://localhost:8000/v1/openapi.json
 *   OPENAPI_FILE if set, read from this local path instead of fetching
 */
import { execFileSync } from 'node:child_process';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT = resolve(__dirname, '../src/api.ts');
const URL = process.env.OPENAPI_URL ?? 'http://localhost:8000/v1/openapi.json';
const FILE = process.env.OPENAPI_FILE;

mkdirSync(dirname(OUT), { recursive: true });

const source = FILE ? resolve(FILE) : URL;
const banner = `// Auto-generated by \`pnpm gen:api\`. Do not edit by hand.\n// Source: ${source}\n`;

let out;
try {
  out = execFileSync('pnpm', ['exec', 'openapi-typescript', source, '--immutable', '--enum'], {
    encoding: 'utf8',
    stdio: ['ignore', 'pipe', 'inherit'],
  });
} catch (err) {
  console.error('openapi-typescript failed. Is the API running on', URL, '?');
  process.exitCode = 1;
  throw err;
}

writeFileSync(OUT, banner + out);
console.log('Wrote', OUT);
