// Auto-generated by `pnpm gen:api`. Do not edit by hand.
// Source: /tmp/openapi.json
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    readonly "/v1/health": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Liveness probe */
        readonly get: operations["get_health_v1_health_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/v1/files/upload": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Upload a file (multipart/form-data) */
        readonly post: operations["upload_v1_files_upload_post"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/v1/files/{file_id}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Download a file */
        readonly get: operations["download_v1_files__file_id__get"];
        readonly put?: never;
        readonly post?: never;
        /** Soft-delete a file */
        readonly delete: operations["delete_v1_files__file_id__delete"];
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/v1/jds/parse": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Parse a JD (sync default, ?stream=1 for SSE) */
        readonly post: operations["parse_v1_jds_parse_post"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/v1/jds": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** List JDs (cursor-paginated) */
        readonly get: operations["list__v1_jds_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/v1/jds/{jd_id}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Get a JD */
        readonly get: operations["get_v1_jds__jd_id__get"];
        readonly put?: never;
        readonly post?: never;
        /** Soft-delete a JD */
        readonly delete: operations["delete_v1_jds__jd_id__delete"];
        readonly options?: never;
        readonly head?: never;
        /** Patch a JD */
        readonly patch: operations["patch_v1_jds__jd_id__patch"];
        readonly trace?: never;
    };
    readonly "/v1/profiles/parse": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Parse a profile (SSE only) */
        readonly post: operations["parse_v1_profiles_parse_post"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/v1/profiles": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** List profiles */
        readonly get: operations["list__v1_profiles_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/v1/profiles/{profile_id}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Get a profile */
        readonly get: operations["get_v1_profiles__profile_id__get"];
        readonly put?: never;
        readonly post?: never;
        /** Soft-delete a profile */
        readonly delete: operations["delete_v1_profiles__profile_id__delete"];
        readonly options?: never;
        readonly head?: never;
        /** Patch a profile */
        readonly patch: operations["patch_v1_profiles__profile_id__patch"];
        readonly trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_upload_v1_files_upload_post */
        readonly Body_upload_v1_files_upload_post: {
            /** File */
            readonly file: string;
            readonly purpose: components["schemas"]["FilePurpose"];
        };
        /**
         * FilePurpose
         * @description Allowed values for the `purpose` form field on POST /v1/files/upload.
         *
         *     The DB column stays VARCHAR(50) so we can extend without ALTER TYPE
         *     (ADR-0005 D4); strict validation lives at the API boundary.
         * @enum {string}
         */
        readonly FilePurpose: FilePurpose;
        /**
         * FileUploadResponse
         * @description Response body for POST /v1/files/upload (and the dedup-replay path).
         *
         *     `replayed=True` means the request body matched an existing
         *     (user_id, sha256) row and we returned the existing file id instead
         *     of inserting a new one (ADR-0005 D5).
         */
        readonly FileUploadResponse: {
            /** Id */
            readonly id: number;
            /** Filename */
            readonly filename: string;
            /** Mime */
            readonly mime: string;
            /** Size Bytes */
            readonly size_bytes: number;
            /** Sha256 */
            readonly sha256: string;
            /** Url */
            readonly url: string;
            /** Replayed */
            readonly replayed: boolean;
        };
        /** HTTPValidationError */
        readonly HTTPValidationError: {
            /** Detail */
            readonly detail?: readonly components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        readonly HealthResponse: {
            /**
             * Status
             * @default ok
             * @constant
             */
            readonly status: "ok";
            /**
             * Version
             * @description API package version
             */
            readonly version: string;
            /**
             * Env
             * @description Runtime environment
             */
            readonly env: string;
            /**
             * Timestamp
             * Format: date-time
             * @description Server time (UTC)
             */
            readonly timestamp: string;
        };
        /**
         * JDDetail
         * @description Full row for GET /v1/jds/{id}.
         */
        readonly JDDetail: {
            /** Id */
            readonly id: number;
            readonly source: components["schemas"]["JdSource"];
            readonly status: components["schemas"]["JdStatus"];
            /** Raw Text */
            readonly raw_text: string | null;
            /** Raw File Id */
            readonly raw_file_id: number | null;
            /** Company */
            readonly company: string | null;
            /** Title */
            readonly title: string | null;
            /** Location */
            readonly location: string | null;
            /** Salary Min */
            readonly salary_min: number | null;
            /** Salary Max */
            readonly salary_max: number | null;
            /** Salary Currency */
            readonly salary_currency: string | null;
            /** Salary Period */
            readonly salary_period: string | null;
            /** Salary Months */
            readonly salary_months: number | null;
            /** Job Level */
            readonly job_level: string | null;
            /** Years Required */
            readonly years_required: number | null;
            /** Education */
            readonly education: string | null;
            /** Hard Skills */
            readonly hard_skills: readonly components["schemas"]["JDSkill"][];
            /** Soft Skills */
            readonly soft_skills: readonly components["schemas"]["JDSkill"][];
            /** Bonus Skills */
            readonly bonus_skills: readonly components["schemas"]["JDSkill"][];
            /** Responsibilities */
            readonly responsibilities: readonly string[];
            /** Description */
            readonly description: string | null;
            /** Parse Confidence */
            readonly parse_confidence: string | null;
            /** Parse Model */
            readonly parse_model: string | null;
            /** Parse Tokens */
            readonly parse_tokens: number | null;
            /** Parse Cost Cny */
            readonly parse_cost_cny: string | null;
            /**
             * Created At
             * Format: date-time
             */
            readonly created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            readonly updated_at: string;
        };
        /**
         * JDListItem
         * @description Light row for listing — strips raw_text / skills / responsibilities.
         */
        readonly JDListItem: {
            /** Id */
            readonly id: number;
            readonly source: components["schemas"]["JdSource"];
            readonly status: components["schemas"]["JdStatus"];
            /** Company */
            readonly company: string | null;
            /** Title */
            readonly title: string | null;
            /** Location */
            readonly location: string | null;
            /** Salary Min */
            readonly salary_min: number | null;
            /** Salary Max */
            readonly salary_max: number | null;
            /** Salary Currency */
            readonly salary_currency: string | null;
            /** Parse Confidence */
            readonly parse_confidence: string | null;
            /**
             * Created At
             * Format: date-time
             */
            readonly created_at: string;
        };
        /** JDListResponse */
        readonly JDListResponse: {
            /** Data */
            readonly data: readonly components["schemas"]["JDListItem"][];
            /** Next Cursor */
            readonly next_cursor?: string | null;
            /**
             * Has More
             * @default false
             */
            readonly has_more: boolean;
        };
        /**
         * JDParseInput
         * @description Body for POST /v1/jds/parse. ADR-0006 D1.
         *
         *     Exactly one of `text` or `file_id` must be provided, and `source`
         *     must agree with the chosen branch.
         */
        readonly JDParseInput: {
            /** Text */
            readonly text?: string | null;
            /** File Id */
            readonly file_id?: number | null;
            /**
             * Source
             * @enum {string}
             */
            readonly source: JDParseInputSource;
        };
        /**
         * JDParseResponse
         * @description Synchronous response. ADR-0006 D4.
         *
         *     On `parse_failed`, `structured` / `confidence` / `tokens` / `cost_cny`
         *     will be null (the HTTP layer raises 422/502 before this is returned;
         *     this shape exists for consistency with the SSE result envelope).
         */
        readonly JDParseResponse: {
            /** Id */
            readonly id: number;
            readonly status: components["schemas"]["JdStatus"];
            readonly structured?: components["schemas"]["JDStructured"] | null;
            /** Confidence */
            readonly confidence?: number | null;
            readonly tokens?: components["schemas"]["JDTokens"] | null;
            /** Cost Cny */
            readonly cost_cny?: string | null;
        };
        /**
         * JDPatchInput
         * @description Allowed fields per ADR-0006 D2.
         *
         *     `raw_text` is the source of truth for re-parsing and is not patchable
         *     (D7); to re-parse with edits, the client should DELETE + POST /parse.
         *     `status` allows `parsing` / `parsed` only — `archived` extension waits
         *     for M4.
         *
         *     `extra="forbid"`: unknown fields are 422 — drift between client and
         *     server should be loud, not silently ignored.
         */
        readonly JDPatchInput: {
            readonly structured?: components["schemas"]["JDStructured"] | null;
            /** Status */
            readonly status?: JDPatchInputStatus | null;
        };
        /** JDSkill */
        readonly JDSkill: {
            /**
             * Name
             * @description 归一化技能名,小写,如 'python','langchain'
             */
            readonly name: string;
            /** Name Raw */
            readonly name_raw: string;
            /** Required */
            readonly required: boolean;
            /** Weight */
            readonly weight: number;
        };
        /** JDStructured */
        readonly JDStructured: {
            /** Company */
            readonly company?: string | null;
            /** Title */
            readonly title: string;
            /** Location */
            readonly location?: string | null;
            /** Salary Min */
            readonly salary_min?: number | null;
            /** Salary Max */
            readonly salary_max?: number | null;
            /**
             * Salary Period
             * @default monthly
             * @enum {string}
             */
            readonly salary_period: JDStructuredSalary_period;
            /**
             * Salary Months
             * @description JD 写明的 'X 薪' 数(14/16 等),代表年终奖月数;JD 未写则 None
             */
            readonly salary_months?: number | null;
            /** Job Level */
            readonly job_level?: JDStructuredJob_level | null;
            /** Years Required */
            readonly years_required?: number | null;
            /** Education */
            readonly education?: JDStructuredEducation | null;
            /** Hard Skills */
            readonly hard_skills?: readonly components["schemas"]["JDSkill"][];
            /** Soft Skills */
            readonly soft_skills?: readonly components["schemas"]["JDSkill"][];
            /** Bonus Skills */
            readonly bonus_skills?: readonly components["schemas"]["JDSkill"][];
            /** Responsibilities */
            readonly responsibilities?: readonly string[];
            /**
             * Description
             * @default
             */
            readonly description: string;
            /**
             * Confidence
             * @description 抽取置信度自评
             */
            readonly confidence: number;
        };
        /** JDTokens */
        readonly JDTokens: {
            /** Input */
            readonly input: number;
            /** Output */
            readonly output: number;
        };
        /**
         * JdSource
         * @description `jd_source` PG ENUM (migration 0003).
         *
         *     M1 API only accepts `text_paste` / `pdf_upload` (ADR-0006 D1);
         *     `image_upload` ships with M1 末 (qwen3.6-vl-flash); `extension_paste`
         *     is reserved for M5+.
         * @enum {string}
         */
        readonly JdSource: JdSource;
        /**
         * JdStatus
         * @description `jd_status` PG ENUM (migration 0003).
         * @enum {string}
         */
        readonly JdStatus: JdStatus;
        /**
         * ProfileDetail
         * @description Full profile + children, returned by GET /v1/profiles/{id}.
         */
        readonly ProfileDetail: {
            /** Id */
            readonly id: number;
            readonly source: components["schemas"]["ProfileSource"];
            readonly status: components["schemas"]["ProfileStatus"];
            /** Raw Text */
            readonly raw_text: string | null;
            /** Raw File Id */
            readonly raw_file_id: number | null;
            readonly structured: components["schemas"]["ProfileStructured"];
            /** Target Salary Min */
            readonly target_salary_min: number | null;
            /** Target Salary Max */
            readonly target_salary_max: number | null;
            /** Parse Model */
            readonly parse_model: string | null;
            /** Parse Tokens */
            readonly parse_tokens: number | null;
            /** Parse Cost Cny */
            readonly parse_cost_cny: string | null;
            readonly stats: components["schemas"]["ProfileStats"];
            /**
             * Created At
             * Format: date-time
             */
            readonly created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            readonly updated_at: string;
        };
        /** ProfileEducationItem */
        readonly ProfileEducationItem: {
            /** School */
            readonly school: string;
            /** Degree */
            readonly degree?: string | null;
            /** Major */
            readonly major?: string | null;
            /** Start Date */
            readonly start_date?: string | null;
            /** End Date */
            readonly end_date?: string | null;
            /** Gpa */
            readonly gpa?: number | null;
            /** Honors */
            readonly honors?: readonly string[];
        };
        /** ProfileExperienceItem */
        readonly ProfileExperienceItem: {
            /** Company */
            readonly company: string;
            /** Title */
            readonly title: string;
            /** Location */
            readonly location?: string | null;
            /** Start Date */
            readonly start_date?: string | null;
            /** End Date */
            readonly end_date?: string | null;
            /**
             * Is Current
             * @default false
             */
            readonly is_current: boolean;
            /**
             * Description
             * @default
             */
            readonly description: string;
            /** Bullets */
            readonly bullets?: readonly string[];
            /** Tech Stack */
            readonly tech_stack?: readonly string[];
            /** Achievements */
            readonly achievements?: readonly string[];
        };
        /**
         * ProfileListItem
         * @description Light row for listing — strips structured children.
         */
        readonly ProfileListItem: {
            /** Id */
            readonly id: number;
            readonly source: components["schemas"]["ProfileSource"];
            readonly status: components["schemas"]["ProfileStatus"];
            /** Full Name */
            readonly full_name: string | null;
            /** Location */
            readonly location: string | null;
            /** Parse Model */
            readonly parse_model: string | null;
            /**
             * Created At
             * Format: date-time
             */
            readonly created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            readonly updated_at: string;
        };
        /** ProfileListResponse */
        readonly ProfileListResponse: {
            /** Data */
            readonly data: readonly components["schemas"]["ProfileListItem"][];
            /** Next Cursor */
            readonly next_cursor?: string | null;
            /**
             * Has More
             * @default false
             */
            readonly has_more: boolean;
        };
        /**
         * ProfileParseInput
         * @description Body for POST /v1/profiles/parse.
         *
         *     Exactly one of `text` or `file_id`; `source` must agree.
         */
        readonly ProfileParseInput: {
            /** Text */
            readonly text?: string | null;
            /** File Id */
            readonly file_id?: number | null;
            /**
             * Source
             * @enum {string}
             */
            readonly source: ProfileParseInputSource;
        };
        /**
         * ProfilePatchInput
         * @description Allowed fields. `raw_text` is the source of truth for re-parsing
         *     and is NOT patchable; to re-parse with edits, DELETE + POST /parse.
         *
         *     Setting `structured` rewrites all children (DELETE-then-INSERT). Skill
         *     `name` collisions inside the new payload are deduped (last write wins)
         *     so the unique constraint `uq_ps_profile_name` won't trip the request.
         */
        readonly ProfilePatchInput: {
            readonly structured?: components["schemas"]["ProfileStructured"] | null;
            /** Status */
            readonly status?: ProfilePatchInputStatus | null;
            /** Target Salary Min */
            readonly target_salary_min?: number | null;
            /** Target Salary Max */
            readonly target_salary_max?: number | null;
        };
        /** ProfileProjectItem */
        readonly ProfileProjectItem: {
            /** Name */
            readonly name: string;
            /** Role */
            readonly role?: string | null;
            /** Start Date */
            readonly start_date?: string | null;
            /** End Date */
            readonly end_date?: string | null;
            /**
             * Description
             * @default
             */
            readonly description: string;
            /** Bullets */
            readonly bullets?: readonly string[];
            /** Tech Stack */
            readonly tech_stack?: readonly string[];
            /** Achievements */
            readonly achievements?: readonly string[];
            /** Repo Url */
            readonly repo_url?: string | null;
            /** Demo Url */
            readonly demo_url?: string | null;
        };
        /** ProfileSkillItem */
        readonly ProfileSkillItem: {
            /**
             * Name
             * @description 归一化技能名,小写,如 'python','langchain'
             */
            readonly name: string;
            /** Name Raw */
            readonly name_raw: string;
            /**
             * Category
             * @default other
             * @enum {string}
             */
            readonly category: ProfileSkillItemCategory;
            /** Level */
            readonly level?: ProfileSkillItemLevel | null;
            /** Years */
            readonly years?: number | null;
        };
        /**
         * ProfileSource
         * @description `profile_source` PG ENUM (migration 0009).
         * @enum {string}
         */
        readonly ProfileSource: ProfileSource;
        /**
         * ProfileStats
         * @description Aggregate counts surfaced on the detail view (AGENT_DESIGN §4.5).
         *
         *     `chunks` stays 0 until S8 wires the rechunk pipeline.
         */
        readonly ProfileStats: {
            /** Experiences */
            readonly experiences: number;
            /** Projects */
            readonly projects: number;
            /** Skills */
            readonly skills: number;
            /** Educations */
            readonly educations: number;
            /**
             * Chunks
             * @default 0
             */
            readonly chunks: number;
        };
        /**
         * ProfileStatus
         * @description `profile_status` PG ENUM (migration 0009).
         * @enum {string}
         */
        readonly ProfileStatus: ProfileStatus;
        /** ProfileStructured */
        readonly ProfileStructured: {
            /** Full Name */
            readonly full_name?: string | null;
            /** Phone */
            readonly phone?: string | null;
            /** Email */
            readonly email?: string | null;
            /** Location */
            readonly location?: string | null;
            /** Summary */
            readonly summary?: string | null;
            /** Target Titles */
            readonly target_titles?: readonly string[];
            /** Experiences */
            readonly experiences?: readonly components["schemas"]["ProfileExperienceItem"][];
            /** Projects */
            readonly projects?: readonly components["schemas"]["ProfileProjectItem"][];
            /** Skills */
            readonly skills?: readonly components["schemas"]["ProfileSkillItem"][];
            /** Educations */
            readonly educations?: readonly components["schemas"]["ProfileEducationItem"][];
        };
        /** ValidationError */
        readonly ValidationError: {
            /** Location */
            readonly loc: readonly (string | number)[];
            /** Message */
            readonly msg: string;
            /** Error Type */
            readonly type: string;
            /** Input */
            readonly input?: unknown;
            /** Context */
            readonly ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    readonly get_health_v1_health_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    readonly upload_v1_files_upload_post: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: {
                readonly "X-User-Id"?: number | null;
            };
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "multipart/form-data": components["schemas"]["Body_upload_v1_files_upload_post"];
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["FileUploadResponse"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly download_v1_files__file_id__get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: {
                readonly "If-None-Match"?: string | null;
                readonly "X-User-Id"?: number | null;
            };
            readonly path: {
                readonly file_id: number;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/octet-stream": unknown;
                };
            };
            /** @description Not modified — content matches If-None-Match */
            readonly 304: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
            /** @description File not found, soft-deleted, or owned by another user */
            readonly 404: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly delete_v1_files__file_id__delete: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: {
                readonly "X-User-Id"?: number | null;
            };
            readonly path: {
                readonly file_id: number;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Soft-deleted */
            readonly 204: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
            /** @description File not found, already deleted, or owned by another user */
            readonly 404: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly parse_v1_jds_parse_post: {
        readonly parameters: {
            readonly query?: {
                readonly stream?: boolean;
            };
            readonly header?: {
                readonly "X-User-Id"?: number | null;
            };
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["JDParseInput"];
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["JDParseResponse"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly list__v1_jds_get: {
        readonly parameters: {
            readonly query?: {
                readonly status?: PathsV1JdsGetParametersQueryStatus | null;
                readonly created_after?: string | null;
                readonly cursor?: string | null;
                readonly limit?: number;
            };
            readonly header?: {
                readonly "X-User-Id"?: number | null;
            };
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["JDListResponse"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly get_v1_jds__jd_id__get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: {
                readonly "X-User-Id"?: number | null;
            };
            readonly path: {
                readonly jd_id: number;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["JDDetail"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly delete_v1_jds__jd_id__delete: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: {
                readonly "X-User-Id"?: number | null;
            };
            readonly path: {
                readonly jd_id: number;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Soft-deleted */
            readonly 204: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            readonly 404: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly patch_v1_jds__jd_id__patch: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: {
                readonly "X-User-Id"?: number | null;
            };
            readonly path: {
                readonly jd_id: number;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["JDPatchInput"];
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["JDDetail"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly parse_v1_profiles_parse_post: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: {
                readonly "X-User-Id"?: number | null;
            };
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["ProfileParseInput"];
            };
        };
        readonly responses: {
            /** @description SSE stream */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": unknown;
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly list__v1_profiles_get: {
        readonly parameters: {
            readonly query?: {
                readonly cursor?: string | null;
                readonly limit?: number;
            };
            readonly header?: {
                readonly "X-User-Id"?: number | null;
            };
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ProfileListResponse"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly get_v1_profiles__profile_id__get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: {
                readonly "X-User-Id"?: number | null;
            };
            readonly path: {
                readonly profile_id: number;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ProfileDetail"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly delete_v1_profiles__profile_id__delete: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: {
                readonly "X-User-Id"?: number | null;
            };
            readonly path: {
                readonly profile_id: number;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Soft-deleted */
            readonly 204: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            readonly 404: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly patch_v1_profiles__profile_id__patch: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: {
                readonly "X-User-Id"?: number | null;
            };
            readonly path: {
                readonly profile_id: number;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["ProfilePatchInput"];
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ProfileDetail"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
export enum PathsV1JdsGetParametersQueryStatus {
    parsing = "parsing",
    parsed = "parsed",
    parse_failed = "parse_failed"
}
export enum FilePurpose {
    jd_pdf = "jd_pdf",
    jd_image = "jd_image",
    profile_pdf = "profile_pdf",
    profile_docx = "profile_docx",
    resume_pdf = "resume_pdf",
    other = "other"
}
export enum JDParseInputSource {
    text_paste = "text_paste",
    pdf_upload = "pdf_upload"
}
export enum JDPatchInputStatus {
    parsing = "parsing",
    parsed = "parsed"
}
export enum JDStructuredSalary_period {
    monthly = "monthly",
    yearly = "yearly"
}
export enum JDStructuredJob_level {
    intern = "intern",
    junior = "junior",
    middle = "middle",
    senior = "senior",
    lead = "lead"
}
export enum JDStructuredEducation {
    "专科" = "\u4E13\u79D1",
    "本科" = "\u672C\u79D1",
    "硕士" = "\u7855\u58EB",
    "博士" = "\u535A\u58EB"
}
export enum JdSource {
    text_paste = "text_paste",
    pdf_upload = "pdf_upload",
    image_upload = "image_upload",
    extension_paste = "extension_paste"
}
export enum JdStatus {
    parsing = "parsing",
    parsed = "parsed",
    parse_failed = "parse_failed"
}
export enum ProfileParseInputSource {
    text_paste = "text_paste",
    pdf_upload = "pdf_upload"
}
export enum ProfilePatchInputStatus {
    parsing = "parsing",
    parsed = "parsed"
}
export enum ProfileSkillItemCategory {
    language = "language",
    framework = "framework",
    tool = "tool",
    database = "database",
    cloud = "cloud",
    other = "other"
}
export enum ProfileSkillItemLevel {
    beginner = "beginner",
    intermediate = "intermediate",
    advanced = "advanced",
    expert = "expert"
}
export enum ProfileSource {
    pdf_upload = "pdf_upload",
    text_paste = "text_paste",
    manual = "manual"
}
export enum ProfileStatus {
    parsing = "parsing",
    parsed = "parsed",
    parse_failed = "parse_failed"
}
